### ISSUE TITLE
Auto Update Version

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#13]
I didn't see an auto updater setting to get either the next beta or the next stable release automatically.
This would save a lot of clicks to get to GitHub releases, DL and install them.

**Comment by rehanvdm** [comment]
At the moment, there aren't beta/stable releases. Only releases 😄.

**Comment by rehanvdm** [comment]
You can check for downloads within the app, on the menu bar here: 
![image](https://user-images.githubusercontent.com/22810856/194287447-06499031-a8c6-4f7d-bd7e-c6b14a307ba1.png)

Then the app should auto update on Windows already and Mac will now also auto-update if you are on the latest version or higher https://github.com/Systanics/CloudGlance/releases/tag/v0.0.94. There is an issue with Linux with AppImage, it can't auto update. 

I have also added friendlier download buttons last week, so that you don't have to go to GitHub every time and search through that long list 
![image](https://user-images.githubusercontent.com/22810856/194288169-bcd3cba2-87e2-4875-9e21-c6e311932a84.png)

**Comment by rehanvdm** [comment]
Let me know if you are still having problem. Closing this for now.
