### ISSUE TITLE
Multiple Profiles SSO Sign-ins in one "Action"

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#15]
Let's say I got plenty of profiles, which I require.

The current state is, that I click through the profiles and per profile I open either the bookmark or the console to get the challenge code/sign-in.
Then I close the sign-in tab and re-click on each profile to get to the actual profile (in the Firefox container).

Is it possible to select multiple profiles and do the token process once, in order to save clicks and time?
This is only possible for profiles located in the same SSO instance, I guess.

**Comment by rehanvdm** [comment]
Are you talking specifically about SSO? 

What do you mean with this:
> re-click on each profile to get to the actual profile 

If it is SSO, then you have to click on the "Continue" button back in Cloud Glance. I might not be understanding the explanation that well. 

There is also an option with settings to help with the scenario where you have many different SSO profiles, I am not sure if that solves your problem? 
![image](https://user-images.githubusercontent.com/22810856/203976984-a0333c5d-461d-469a-97b3-56af7ff9c208.png)

> Is it possible to select multiple profiles and do the token process once, in order to save clicks and time?
This is 100% my goal, if I can better understand the problem. 

An upcoming feature of Cloud Glance will be "Routines", where you can then just click a single button that then stitches together many actions (open AWS profiles, connect to a bastion, etc) together. So that you don't have to click 100's of times every morning. Not sure if that would be useful to you?
 
I also want to remove the "Continue" button when doing SSO sign-in should be able to just poll, at least that is what I think the AWS CLI is doing.

**Comment by michaelfecher** [comment]
That option "Open SSO login" didn't help.

My issue in short, hopefully much clearer:
When clicking on a profile, it always comes up the authorization part (1 click) and then a popup in CloudGlance, which I need to click additionally and shouldn't forget about (2nd click). ;)
This process doesn't consider if I'm already authorized at the same SSO start URL.

However, you opened up the vision of the "Routines", which may be the thing I'm looking for. ;)

**Comment by rehanvdm** [comment]
Ahh thanks, that makes more sense. 

I made some improvements to the current SSO Login flow in this relese https://github.com/Systanics/CloudGlance/releases/tag/v0.0.105. It doesn't yet _"Open Multiple Profiles SSO Sign-ins in one Action"_ that will be Routines is on the roadmap as mentioned.

> This process doesn't consider if I'm already authorized at the same SSO start URL.

It has always done this, **see the video in the release above**. I only have to login once, then the other two profiles have the same SSO Start URL. So then I don't have to Login again. I just need to click on "Approve" which is an AWS SSO requirement. We can't just assume the Role without user interaction.

**Comment by rehanvdm** [comment]
Closing for now. Will post a comment here when the Routines feature has dropped.
