### ISSUE TITLE
Export of environment variables generates Windows only commands

### ISSUE THREAD

**Issue by michaelfecher** [Systanics/CloudGlance#17]
I am working in the WSL, when dealing with AWS.
CloudGlance is installed on Windows directly. 

**To Reproduce**
1. Go to "Profiles and select one of the existing profiles
2. Log in / Get authorization
3. Back to CloudGlance profile and click on "Copy temporary environment variables to clipboard"
4. Paste the content to inspect

**Expected behavior**
The setting of the env vars should be OS dependent.
Means you should be able to select your OS in the CloudGlance settings.

**Desktop (please be as specific as possible):**
Windows 10 as Host
Ubuntu 20.04 (WSL)

**App version (click on the "Boundaries" menu item or at the bottom of the settings page)**
Version 0.0.105

**Comment by rehanvdm** [comment]
Yes, this can be added, makes sense, have not thought about this use case before.

> Means you should be able to select your OS in the CloudGlance settings.

I think that will be a good place to set it yes, a global setting. I will make it a select box, that will default to your current OS. It will have three options:
- Windows
- Unix
- Windows and Unix (this one will then put two buttons in the menu, instead of just one, so one for each OS)

**Comment by rehanvdm** [comment]
Added in this release: https://github.com/Systanics/CloudGlance/releases/tag/v0.0.106 see release notes for usage
