### ISSUE TITLE
Hosted profiles must use https for the git repo url

### ISSUE THREAD

**Issue by NicolasRitouet** [Systanics/CloudGlance#3]
**Describe the bug**
When trying to add an hosted profile using a git repo, CloudGlane requires an http url. Since I'm exclusively using ssh (git://...) to connect to my repos, I get an error saying that I might not have permission to access the repo.
It should either allow to use ssh (my preference) or ask for github credentials.
Also, after the error is displayed, the hosted profile is not even saved.

**To Reproduce**
requirements: git is installed and properly configured in CloudGlance.
1. Go to 'configuration'
2. Click on 'hosted groups'
3. Click on button 'create hosted profile'
4. Enter git url (using https url)
5. Click on button 'add'
6. error message says that it could not read username and that I might not have permission / device not configured.

**Expected behavior**
I guess that since I'm using ssh to access my git repos, the setup to connect with https hasn't been made.
I expect to be able to use ssh or at least to have options to setup https.
Oh yeah, and I do expect the profile to be saved after I get the notification "profile saved" 😅

**Screenshots**
<img width="794" alt="Capture d’écran 2022-08-19 à 15 42 41" src="https://user-images.githubusercontent.com/205134/185632478-ede4d618-ca08-4d69-a252-aaec333d5b4f.png">

**Desktop (please be as specific as possible):**
Macosx

**App version (click on the "Boundaries" menu item or at the bottom of the settings page)**
Version 0.0.74

**Additional context**
Love the idea of the tool, thx a lot for your work @rehanvdm , I hope I can help make it better :)

**Comment by rehanvdm** [comment]
> I do expect the profile to be saved after I get the notification "profile saved" 😅 
Indeed 😂

Appreciate the feedback. I will look into this, currently only HTTPS is working. A side note- it assumes that you are already signed in with the git CLI. I don't prompt and verify that if you are not. So there are a few things that can be improved around this area.

**Comment by rehanvdm** [comment]
Fixed, will be in the next release. @NicolasRitouet note that Cloud Glance does not ask for a passphrase when reading the private key. You would have to use some other mechanism to provide that before Cloud Glance calls the `git` commands. There are various ways to do this, for me on Windows, I followed: https://lightrun.com/answers/microsoft-vscode-git-support-git-with-private-key-password 
> A workaround for Windows 10:
>
 > 1.  Make Git use the OpenSSH that comes with Windows instead of the one that comes with Git. git config --global core.sshCommand "C:/Windows/System32/OpenSSH/ssh.exe"
>2.    Set the ssh-agent service (not the one that comes with git) to run automatically. Open Task Manager, Services tab, click Open Services. Find OpenSSH Authentication Agent, open properties, set Startup Type to Automatic, hit OK. Also start the service or restart your computer.
>3.    Add your password protected key to the agent. ssh-add It should automatically pick up keys stored in C:\Users\%USERNAME%\.ssh which is where ssh-keygen creates them. Enter your password(s) at the prompt.

Then you need to clear this specific git profile from the settings. No one else needs to do this going forward, your config is just in the wrong state (it will stay in the `Checking` state indefinitely) due to this bug. To fix it, go to your Cloud Glance settings folder, you will see a `confg.json` file. Here is an example of what that contents would look like: 

``` json
{
  "managed": [
    {
      "name": "Test",
      "git_repo": "https://github.com/rehanvdm/XXX.git",
      "git_branch": "master",
      "last_merged_at": "2022-09-21T19:22:38.973Z",
      "last_checked_at": "2022-10-06T04:20:30.027Z"
    },
    {
      "name": "boundaries-config",
      "git_repo": "git@github.com:Systanics/YYY.git",
      "git_branch": "master"
    }
  ]
}
```

Delete all entries that specify the git_repo to be pulled over SSH, so in my case only the second entry, the first entry should stay as that is an HTTPS one and that is fine. So the contents of your file should then be:

``` json
{
  "managed": [
    {
      "name": "Test",
      "git_repo": "https://github.com/rehanvdm/XXX.git",
      "git_branch": "master",
      "last_merged_at": "2022-09-21T19:22:38.973Z",
      "last_checked_at": "2022-10-06T04:20:30.027Z"
    }
  ]
}
```

Using git over SSH will now work.

**Comment by rehanvdm** [comment]
Fixed in release https://github.com/Systanics/CloudGlance/releases/tag/v0.0.95
